### ISSUE TITLE
Upload testing & API

### ISSUE THREAD

**Issue by MattIPv4** [n8henrie/fastcli#1]
Hi there,

It'd be absolutely amazing if this was made more modular (an API) so that it could be called from within other programs to determine the results.

Further, it would be awesome if this tested the upload speed as well as the download speed, much like the actual fast.com site does.

**Comment by n8henrie** [comment]
Thanks for the suggestions.

I didn't realize Fast.com now shows upload speeds -- I'm pretty sure it didn't at the time I wrote this.

These feature requests seem reasonable, I'll consider implementing them as time allows.

**Comment by MattIPv4** [comment]
@n8henrie Awesome, thank you! Fast.com allows for faster speeds than most servers on speedtest.net, so I'd love to migrate my testing over to Fast.com and your lib once upload testing is supported. :)

**Comment by n8henrie** [comment]
I made some progress updating the library for the v2 API [on the dev branch](https://github.com/n8henrie/fastcli/tree/dev), but I can't figure out a good way to do the upload speeds. I've searched for similar libraries in other languages and they all seem to be doing some kind of scraping, which seems like the wrong way to go about it.

If anybody had recommendations here, I'm all ears. Otherwise I will likely close the issue in the near future, since I've given it my best shot, and there have been no other volunteers in the last 6 months.
